# Generated by Django 3.2.5 on 2021-07-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210729_2012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
